colors = (
    None,
    'IndianRed',
    'LightCoral',
    'Salmon',
    'DarkSalmon',
    'LightSalmon',
    'Crimson',
    'Red',
    'FireBrick',
    'DarkRed',
        
    'Pink',
    'LightPink',
    'HotPink',
    'DeepPink',
    'MediumVioletRed',
    'PaleVioletRed',
        
    'LightSalmon',
    'Coral',
    'Tomato',
    'OrangeRed',
    'DarkOrange',
    'Orange',
        
    'Gold',
    'Yellow',
    'LightYellow',
    'LemonChiffon',
    'LightGoldenrodYellow',
    'PapayaWhip',
    'Moccasin',
    'PeachPuff',
    'PaleGoldenrod',
    'Khaki',
    'DarkKhaki',
        
    'Lavender',
    'Thistle',
    'Plum',
    'Violet',
    'Orchid',
    'Fuchsia',
    'Magenta',
    'MediumOrchid',
    'MediumPurple',
    'Amethyst',
    'BlueViolet',
    'DarkViolet',
    'DarkOrchid',
    'DarkMagenta',
    'Purple',
    'Indigo',
    'SlateBlue',
    'DarkSlateBlue',
    'MediumSlateBlue',
        
    'GreenYellow',
    'Chartreuse',
    'LawnGreen',
    'Lime',
    'LimeGreen',
    'PaleGreen',
    'LightGreen',
    'MediumSpringGreen',
    'SpringGreen',
    'MediumSeaGreen',
    'SeaGreen',
    'ForestGreen',
    'Green',
    'DarkGreen',
    'YellowGreen',
    'OliveDrab',
    'Olive',
    'DarkOliveGreen',
    'MediumAquamarine',
    'DarkSeaGreen',
    'LightSeaGreen',
    'DarkCyan',
    'Teal',
        
    'Aqua',
    'Cyan',
    'LightCyan',
    'PaleTurquoise',
    'Aquamarine',
    'Turquoise',
    'MediumTurquoise',
    'DarkTurquoise',
    'CadetBlue',
    'SteelBlue',
    'LightSteelBlue',
    'PowderBlue',
    'LightBlue',
    'SkyBlue',
    'LightSkyBlue',
    'DeepSkyBlue',
    'DodgerBlue',
    'CornflowerBlue',
    'MediumSlateBlue',
    'RoyalBlue',
    'Blue',
    'MediumBlue',
    'DarkBlue',
    'Navy',
    'MidnightBlue',
        
    'Cornsilk',
    'BlanchedAlmond',
    'Bisque',
    'NavajoWhite',
    'Wheat',
    'BurlyWood',
    'Tan',
    'RosyBrown',
    'SandyBrown',
    'Goldenrod',
    'DarkGoldenrod',
    'Peru',
    'Chocolate',
    'SaddleBrown',
    'Sienna',
    'Brown',
    'Maroon',
        
    'White',
    'Snow',
    'Honeydew',
    'MintCream',
    'Azure',
    'AliceBlue',
    'GhostWhite',
    'WhiteSmoke',
    'Seashell',
    'Beige',
    'OldLace',
    'FloralWhite',
    'Ivory',
    'AntiqueWhite',
    'Linen',
    'LavenderBlush',
    'MistyRose',
        
    'Gainsboro',
    'LightGrey',
    'Silver',
    'DarkGray',
    'Gray',
    'DimGray',
    'LightSlateGray',
    'SlateGray',
    'DarkSlateGray',
    'Black'
)




loweredColors = (
    None,
    'indianred',
    'lightcoral',
    'salmon',
    'darksalmon',
    'lightsalmon',
    'crimson',
    'red',
    'firebrick',
    'darkred',
        
    'pink',
    'lightpink',
    'hotpink',
    'deeppink',
    'mediumvioletred',
    'palevioletred',
        
    'lightsalmon',
    'coral',
    'tomato',
    'orangered',
    'darkorange',
    'orange',
        
    'gold',
    'yellow',
    'lightyellow',
    'lemonchiffon',
    'lightgoldenrodyellow',
    'papayawhip',
    'moccasin',
    'peachpuff',
    'palegoldenrod',
    'khaki',
    'darkkhaki',
        
    'lavender',
    'thistle',
    'plum',
    'violet',
    'orchid',
    'fuchsia',
    'magenta',
    'mediumorchid',
    'mediumpurple',
    'amethyst',
    'blueviolet',
    'darkviolet',
    'darkorchid',
    'darkmagenta',
    'purple',
    'indigo',
    'slateblue',
    'darkslateblue',
    'mediumslateblue',
        
    'greenyellow',
    'chartreuse',
    'lawngreen',
    'lime',
    'limegreen',
    'palegreen',
    'lightgreen',
    'mediumspringgreen',
    'springgreen',
    'mediumseagreen',
    'seagreen',
    'forestgreen',
    'green',
    'darkgreen',
    'yellowgreen',
    'olivedrab',
    'olive',
    'darkolivegreen',
    'mediumaquamarine',
    'darkseagreen',
    'lightseagreen',
    'darkcyan',
    'teal',
        
    'aqua',
    'cyan',
    'lightcyan',
    'paleturquoise',
    'aquamarine',
    'turquoise',
    'mediumturquoise',
    'darkturquoise',
    'cadetblue',
    'steelblue',
    'lightsteelblue',
    'powderblue',
    'lightblue',
    'skyblue',
    'lightskyblue',
    'deepskyblue',
    'dodgerblue',
    'cornflowerblue',
    'mediumslateblue',
    'royalblue',
    'blue',
    'mediumblue',
    'darkblue',
    'navy',
    'midnightblue',
        
    'cornsilk',
    'blanchedalmond',
    'bisque',
    'navajowhite',
    'wheat',
    'burlywood',
    'tan',
    'rosybrown',
    'sandybrown',
    'goldenrod',
    'darkgoldenrod',
    'peru',
    'chocolate',
    'saddlebrown',
    'sienna',
    'brown',
    'maroon',
        
    'white',
    'snow',
    'honeydew',
    'mintcream',
    'azure',
    'aliceblue',
    'ghostwhite',
    'whitesmoke',
    'seashell',
    'beige',
    'oldlace',
    'floralwhite',
    'ivory',
    'antiquewhite',
    'linen',
    'lavenderblush',
    'mistyrose',
        
    'gainsboro',
    'lightgrey',
    'silver',
    'darkgray',
    'gray',
    'dimgray',
    'lightslategray',
    'slategray',
    'darkslategray',
    'black'      
)





coloredColors = (
    None,
    '[COLOR indianred]IndianRed[/COLOR]',
    '[COLOR lightcoral]LightCoral[/COLOR]',
    '[COLOR salmon]Salmon[/COLOR]',
    '[COLOR darksalmon]DarkSalmon[/COLOR]',
    '[COLOR lightsalmon]LightSalmon[/COLOR]',
    '[COLOR crimson]Crimson[/COLOR]',
    '[COLOR red]Red[/COLOR]',
    '[COLOR firebrick]FireBrick[/COLOR]',
    '[COLOR darkred]DarkRed[/COLOR]',
    
    '[COLOR pink]Pink[/COLOR]',
    '[COLOR lightpink]LightPink[/COLOR]',
    '[COLOR hotpink]HotPink[/COLOR]',
    '[COLOR deeppink]DeepPink[/COLOR]',
    '[COLOR mediumvioletred]MediumVioletRed[/COLOR]',
    '[COLOR palevioletred]PaleVioletRed[/COLOR]',
    
    '[COLOR lightsalmon]LightSalmon[/COLOR]',
    '[COLOR coral]Coral[/COLOR]',
    '[COLOR tomato]Tomato[/COLOR]',
    '[COLOR orangered]OrangeRed[/COLOR]',
    '[COLOR darkorange]DarkOrange[/COLOR]',
    '[COLOR orange]Orange[/COLOR]',
    
    '[COLOR gold]Gold[/COLOR]',
    '[COLOR yellow]Yellow[/COLOR]',
    '[COLOR lightyellow]LightYellow[/COLOR]',
    '[COLOR lemonchiffon]LemonChiffon[/COLOR]',
    '[COLOR lightgoldenrodyellow]LightGoldenrodYellow[/COLOR]',
    '[COLOR papayawhip]PapayaWhip[/COLOR]',
    '[COLOR moccasin]Moccasin[/COLOR]',
    '[COLOR peachpuff]PeachPuff[/COLOR]',
    '[COLOR palegoldenrod]PaleGoldenrod[/COLOR]',
    '[COLOR khaki]Khaki[/COLOR]',
    '[COLOR darkkhaki]DarkKhaki[/COLOR]',
    
    '[COLOR lavender]Lavender[/COLOR]',
    '[COLOR thistle]Thistle[/COLOR]',
    '[COLOR plum]Plum[/COLOR]',
    '[COLOR violet]Violet[/COLOR]',
    '[COLOR orchid]Orchid[/COLOR]',
    '[COLOR fuchsia]Fuchsia[/COLOR]',
    '[COLOR magenta]Magenta[/COLOR]',
    '[COLOR mediumorchid]MediumOrchid[/COLOR]',
    '[COLOR mediumpurple]MediumPurple[/COLOR]',
    '[COLOR amethyst]Amethyst[/COLOR]',
    '[COLOR blueviolet]BlueViolet[/COLOR]',
    '[COLOR darkviolet]DarkViolet[/COLOR]',
    '[COLOR darkorchid]DarkOrchid[/COLOR]',
    '[COLOR darkmagenta]DarkMagenta[/COLOR]',
    '[COLOR purple]Purple[/COLOR]',
    '[COLOR indigo]Indigo[/COLOR]',
    '[COLOR slateblue]SlateBlue[/COLOR]',
    '[COLOR darkslateblue]DarkSlateBlue[/COLOR]',
    '[COLOR mediumslateblue]MediumSlateBlue[/COLOR]',
    
    '[COLOR greenyellow]GreenYellow[/COLOR]',
    '[COLOR chartreuse]Chartreuse[/COLOR]',
    '[COLOR lawngreen]LawnGreen[/COLOR]',
    '[COLOR lime]Lime[/COLOR]',
    '[COLOR limegreen]LimeGreen[/COLOR]',
    '[COLOR palegreen]PaleGreen[/COLOR]',
    '[COLOR lightgreen]LightGreen[/COLOR]',
    '[COLOR mediumspringgreen]MediumSpringGreen[/COLOR]',
    '[COLOR springgreen]SpringGreen[/COLOR]',
    '[COLOR mediumseagreen]MediumSeaGreen[/COLOR]',
    '[COLOR seagreen]SeaGreen[/COLOR]',
    '[COLOR forestgreen]ForestGreen[/COLOR]',
    '[COLOR green]Green[/COLOR]',
    '[COLOR darkgreen]DarkGreen[/COLOR]',
    '[COLOR yellowgreen]YellowGreen[/COLOR]',
    '[COLOR olivedrab]OliveDrab[/COLOR]',
    '[COLOR olive]Olive[/COLOR]',
    '[COLOR darkolivegreen]DarkOliveGreen[/COLOR]',
    '[COLOR mediumaquamarine]MediumAquamarine[/COLOR]',
    '[COLOR darkseagreen]DarkSeaGreen[/COLOR]',
    '[COLOR lightseagreen]LightSeaGreen[/COLOR]',
    '[COLOR darkcyan]DarkCyan[/COLOR]',
    '[COLOR teal]Teal[/COLOR]',
    
    '[COLOR aqua]Aqua[/COLOR]',
    '[COLOR cyan]Cyan[/COLOR]',
    '[COLOR lightcyan]LightCyan[/COLOR]',
    '[COLOR paleturquoise]PaleTurquoise[/COLOR]',
    '[COLOR aquamarine]Aquamarine[/COLOR]',
    '[COLOR turquoise]Turquoise[/COLOR]',
    '[COLOR mediumturquoise]MediumTurquoise[/COLOR]',
    '[COLOR darkturquoise]DarkTurquoise[/COLOR]',
    '[COLOR cadetblue]CadetBlue[/COLOR]',
    '[COLOR steelblue]SteelBlue[/COLOR]',
    '[COLOR lightsteelblue]LightSteelBlue[/COLOR]',
    '[COLOR powderblue]PowderBlue[/COLOR]',
    '[COLOR lightblue]LightBlue[/COLOR]',
    '[COLOR skyblue]SkyBlue[/COLOR]',
    '[COLOR lightskyblue]LightSkyBlue[/COLOR]',
    '[COLOR deepskyblue]DeepSkyBlue[/COLOR]',
    '[COLOR dodgerblue]DodgerBlue[/COLOR]',
    '[COLOR cornflowerblue]CornflowerBlue[/COLOR]',
    '[COLOR mediumslateblue]MediumSlateBlue[/COLOR]',
    '[COLOR royalblue]RoyalBlue[/COLOR]',
    '[COLOR blue]Blue[/COLOR]',
    '[COLOR mediumblue]MediumBlue[/COLOR]',
    '[COLOR darkblue]DarkBlue[/COLOR]',
    '[COLOR navy]Navy[/COLOR]',
    '[COLOR midnightblue]MidnightBlue[/COLOR]',
    
    '[COLOR cornsilk]Cornsilk[/COLOR]',
    '[COLOR blanchedalmond]BlanchedAlmond[/COLOR]',
    '[COLOR bisque]Bisque[/COLOR]',
    '[COLOR navajowhite]NavajoWhite[/COLOR]',
    '[COLOR wheat]Wheat[/COLOR]',
    '[COLOR burlywood]BurlyWood[/COLOR]',
    '[COLOR tan]Tan[/COLOR]',
    '[COLOR rosybrown]RosyBrown[/COLOR]',
    '[COLOR sandybrown]SandyBrown[/COLOR]',
    '[COLOR goldenrod]Goldenrod[/COLOR]',
    '[COLOR darkgoldenrod]DarkGoldenrod[/COLOR]',
    '[COLOR peru]Peru[/COLOR]',
    '[COLOR chocolate]Chocolate[/COLOR]',
    '[COLOR saddlebrown]SaddleBrown[/COLOR]',
    '[COLOR sienna]Sienna[/COLOR]',
    '[COLOR brown]Brown[/COLOR]',
    '[COLOR maroon]Maroon[/COLOR]',
    
    '[COLOR white]White[/COLOR]',
    '[COLOR snow]Snow[/COLOR]',
    '[COLOR honeydew]Honeydew[/COLOR]',
    '[COLOR mintcream]MintCream[/COLOR]',
    '[COLOR azure]Azure[/COLOR]',
    '[COLOR aliceblue]AliceBlue[/COLOR]',
    '[COLOR ghostwhite]GhostWhite[/COLOR]',
    '[COLOR whitesmoke]WhiteSmoke[/COLOR]',
    '[COLOR seashell]Seashell[/COLOR]',
    '[COLOR beige]Beige[/COLOR]',
    '[COLOR oldlace]OldLace[/COLOR]',
    '[COLOR floralwhite]FloralWhite[/COLOR]',
    '[COLOR ivory]Ivory[/COLOR]',
    '[COLOR antiquewhite]AntiqueWhite[/COLOR]',
    '[COLOR linen]Linen[/COLOR]',
    '[COLOR lavenderblush]LavenderBlush[/COLOR]',
    '[COLOR mistyrose]MistyRose[/COLOR]',
    
    '[COLOR gainsboro]Gainsboro[/COLOR]',
    '[COLOR lightgrey]LightGrey[/COLOR]',
    '[COLOR silver]Silver[/COLOR]',
    '[COLOR darkgray]DarkGray[/COLOR]',
    '[COLOR gray]Gray[/COLOR]',
    '[COLOR dimgray]DimGray[/COLOR]',
    '[COLOR lightslategray]LightSlateGray[/COLOR]',
    '[COLOR slategray]SlateGray[/COLOR]',
    '[COLOR darkslategray]DarkSlateGray[/COLOR]',
    '[COLOR black]Black[/COLOR]'
)


loweredToColored = {
    None:None,
    'indianred':'[COLOR indianred]IndianRed[/COLOR]',
    'lightcoral':'[COLOR lightcoral]LightCoral[/COLOR]',
    'salmon':'[COLOR salmon]Salmon[/COLOR]',
    'darksalmon':'[COLOR darksalmon]DarkSalmon[/COLOR]',
    'lightsalmon':'[COLOR lightsalmon]LightSalmon[/COLOR]',
    'crimson':'[COLOR crimson]Crimson[/COLOR]',
    'red':'[COLOR red]Red[/COLOR]',
    'firebrick':'[COLOR firebrick]FireBrick[/COLOR]',
    'darkred':'[COLOR darkred]DarkRed[/COLOR]',
    
    'pink':'[COLOR pink]Pink[/COLOR]',
    'lightpink':'[COLOR lightpink]LightPink[/COLOR]',
    'hotpink':'[COLOR hotpink]HotPink[/COLOR]',
    'deeppink':'[COLOR deeppink]DeepPink[/COLOR]',
    'mediumvioletred':'[COLOR mediumvioletred]MediumVioletRed[/COLOR]',
    'palevioletred':'[COLOR palevioletred]PaleVioletRed[/COLOR]',
    
    'lightsalmon':'[COLOR lightsalmon]LightSalmon[/COLOR]',
    'coral':'[COLOR coral]Coral[/COLOR]',
    'tomato':'[COLOR tomato]Tomato[/COLOR]',
    'orangered':'[COLOR orangered]OrangeRed[/COLOR]',
    'darkorange':'[COLOR darkorange]DarkOrange[/COLOR]',
    'orange':'[COLOR orange]Orange[/COLOR]',
    
    'gold':'[COLOR gold]Gold[/COLOR]',
    'yellow':'[COLOR yellow]Yellow[/COLOR]',
    'lightyellow':'[COLOR lightyellow]LightYellow[/COLOR]',
    'lemonchiffon':'[COLOR lemonchiffon]LemonChiffon[/COLOR]',
    'lightgoldenrodyellow':'[COLOR lightgoldenrodyellow]LightGoldenrodYellow[/COLOR]',
    'papayawhip':'[COLOR papayawhip]PapayaWhip[/COLOR]',
    'moccasin':'[COLOR moccasin]Moccasin[/COLOR]',
    'peachpuff':'[COLOR peachpuff]PeachPuff[/COLOR]',
    'palegoldenrod':'[COLOR palegoldenrod]PaleGoldenrod[/COLOR]',
    'khaki':'[COLOR khaki]Khaki[/COLOR]',
    'darkkhaki':'[COLOR darkkhaki]DarkKhaki[/COLOR]',
    
    'lavender':'[COLOR lavender]Lavender[/COLOR]',
    'thistle':'[COLOR thistle]Thistle[/COLOR]',
    'plum':'[COLOR plum]Plum[/COLOR]',
    'violet':'[COLOR violet]Violet[/COLOR]',
    'orchid':'[COLOR orchid]Orchid[/COLOR]',
    'fuchsia':'[COLOR fuchsia]Fuchsia[/COLOR]',
    'magenta':'[COLOR magenta]Magenta[/COLOR]',
    'mediumorchid':'[COLOR mediumorchid]MediumOrchid[/COLOR]',
    'mediumpurple':'[COLOR mediumpurple]MediumPurple[/COLOR]',
    'amethyst':'[COLOR amethyst]Amethyst[/COLOR]',
    'blueviolet':'[COLOR blueviolet]BlueViolet[/COLOR]',
    'darkviolet':'[COLOR darkviolet]DarkViolet[/COLOR]',
    'darkorchid':'[COLOR darkorchid]DarkOrchid[/COLOR]',
    'darkmagenta':'[COLOR darkmagenta]DarkMagenta[/COLOR]',
    'purple':'[COLOR purple]Purple[/COLOR]',
    'indigo':'[COLOR indigo]Indigo[/COLOR]',
    'slateblue':'[COLOR slateblue]SlateBlue[/COLOR]',
    'darkslateblue':'[COLOR darkslateblue]DarkSlateBlue[/COLOR]',
    'mediumslateblue':'[COLOR mediumslateblue]MediumSlateBlue[/COLOR]',
    
    'greenyellow':'[COLOR greenyellow]GreenYellow[/COLOR]',
    'chartreuse':'[COLOR chartreuse]Chartreuse[/COLOR]',
    'lawngreen':'[COLOR lawngreen]LawnGreen[/COLOR]',
    'lime':'[COLOR lime]Lime[/COLOR]',
    'limegreen':'[COLOR limegreen]LimeGreen[/COLOR]',
    'palegreen':'[COLOR palegreen]PaleGreen[/COLOR]',
    'lightgreen':'[COLOR lightgreen]LightGreen[/COLOR]',
    'mediumspringgreen':'[COLOR mediumspringgreen]MediumSpringGreen[/COLOR]',
    'springgreen':'[COLOR springgreen]SpringGreen[/COLOR]',
    'mediumseagreen':'[COLOR mediumseagreen]MediumSeaGreen[/COLOR]',
    'seagreen':'[COLOR seagreen]SeaGreen[/COLOR]',
    'forestgreen':'[COLOR forestgreen]ForestGreen[/COLOR]',
    'green':'[COLOR green]Green[/COLOR]',
    'darkgreen':'[COLOR darkgreen]DarkGreen[/COLOR]',
    'yellowgreen':'[COLOR yellowgreen]YellowGreen[/COLOR]',
    'olivedrab':'[COLOR olivedrab]OliveDrab[/COLOR]',
    'olive':'[COLOR olive]Olive[/COLOR]',
    'darkolivegreen':'[COLOR darkolivegreen]DarkOliveGreen[/COLOR]',
    'mediumaquamarine':'[COLOR mediumaquamarine]MediumAquamarine[/COLOR]',
    'darkseagreen':'[COLOR darkseagreen]DarkSeaGreen[/COLOR]',
    'lightseagreen':'[COLOR lightseagreen]LightSeaGreen[/COLOR]',
    'darkcyan':'[COLOR darkcyan]DarkCyan[/COLOR]',
    'teal':'[COLOR teal]Teal[/COLOR]',
    
    'aqua':'[COLOR aqua]Aqua[/COLOR]',
    'cyan':'[COLOR cyan]Cyan[/COLOR]',
    'lightcyan':'[COLOR lightcyan]LightCyan[/COLOR]',
    'paleturquoise':'[COLOR paleturquoise]PaleTurquoise[/COLOR]',
    'aquamarine':'[COLOR aquamarine]Aquamarine[/COLOR]',
    'turquoise':'[COLOR turquoise]Turquoise[/COLOR]',
    'mediumturquoise':'[COLOR mediumturquoise]MediumTurquoise[/COLOR]',
    'darkturquoise':'[COLOR darkturquoise]DarkTurquoise[/COLOR]',
    'cadetblue':'[COLOR cadetblue]CadetBlue[/COLOR]',
    'steelblue':'[COLOR steelblue]SteelBlue[/COLOR]',
    'lightsteelblue':'[COLOR lightsteelblue]LightSteelBlue[/COLOR]',
    'powderblue':'[COLOR powderblue]PowderBlue[/COLOR]',
    'lightblue':'[COLOR lightblue]LightBlue[/COLOR]',
    'skyblue':'[COLOR skyblue]SkyBlue[/COLOR]',
    'lightskyblue':'[COLOR lightskyblue]LightSkyBlue[/COLOR]',
    'deepskyblue':'[COLOR deepskyblue]DeepSkyBlue[/COLOR]',
    'dodgerblue':'[COLOR dodgerblue]DodgerBlue[/COLOR]',
    'cornflowerblue':'[COLOR cornflowerblue]CornflowerBlue[/COLOR]',
    'mediumslateblue':'[COLOR mediumslateblue]MediumSlateBlue[/COLOR]',
    'royalblue':'[COLOR royalblue]RoyalBlue[/COLOR]',
    'blue':'[COLOR blue]Blue[/COLOR]',
    'mediumblue':'[COLOR mediumblue]MediumBlue[/COLOR]',
    'darkblue':'[COLOR darkblue]DarkBlue[/COLOR]',
    'navy':'[COLOR navy]Navy[/COLOR]',
    'midnightblue':'[COLOR midnightblue]MidnightBlue[/COLOR]',
    
    'cornsilk':'[COLOR cornsilk]Cornsilk[/COLOR]',
    'blanchedalmond':'[COLOR blanchedalmond]BlanchedAlmond[/COLOR]',
    'bisque':'[COLOR bisque]Bisque[/COLOR]',
    'navajowhite':'[COLOR navajowhite]NavajoWhite[/COLOR]',
    'wheat':'[COLOR wheat]Wheat[/COLOR]',
    'burlywood':'[COLOR burlywood]BurlyWood[/COLOR]',
    'tan':'[COLOR tan]Tan[/COLOR]',
    'rosybrown':'[COLOR rosybrown]RosyBrown[/COLOR]',
    'sandybrown':'[COLOR sandybrown]SandyBrown[/COLOR]',
    'goldenrod':'[COLOR goldenrod]Goldenrod[/COLOR]',
    'darkgoldenrod':'[COLOR darkgoldenrod]DarkGoldenrod[/COLOR]',
    'peru':'[COLOR peru]Peru[/COLOR]',
    'chocolate':'[COLOR chocolate]Chocolate[/COLOR]',
    'saddlebrown':'[COLOR saddlebrown]SaddleBrown[/COLOR]',
    'sienna':'[COLOR sienna]Sienna[/COLOR]',
    'brown':'[COLOR brown]Brown[/COLOR]',
    'maroon':'[COLOR maroon]Maroon[/COLOR]',
    
    'white':'[COLOR white]White[/COLOR]',
    'snow':'[COLOR snow]Snow[/COLOR]',
    'honeydew':'[COLOR honeydew]Honeydew[/COLOR]',
    'mintcream':'[COLOR mintcream]MintCream[/COLOR]',
    'azure':'[COLOR azure]Azure[/COLOR]',
    'aliceblue':'[COLOR aliceblue]AliceBlue[/COLOR]',
    'ghostwhite':'[COLOR ghostwhite]GhostWhite[/COLOR]',
    'whitesmoke':'[COLOR whitesmoke]WhiteSmoke[/COLOR]',
    'seashell':'[COLOR seashell]Seashell[/COLOR]',
    'beige':'[COLOR beige]Beige[/COLOR]',
    'oldlace':'[COLOR oldlace]OldLace[/COLOR]',
    'floralwhite':'[COLOR floralwhite]FloralWhite[/COLOR]',
    'ivory':'[COLOR ivory]Ivory[/COLOR]',
    'antiquewhite':'[COLOR antiquewhite]AntiqueWhite[/COLOR]',
    'linen':'[COLOR linen]Linen[/COLOR]',
    'lavenderblush':'[COLOR lavenderblush]LavenderBlush[/COLOR]',
    'mistyrose':'[COLOR mistyrose]MistyRose[/COLOR]',
    
    'gainsboro':'[COLOR gainsboro]Gainsboro[/COLOR]',
    'lightgrey':'[COLOR lightgrey]LightGrey[/COLOR]',
    'silver':'[COLOR silver]Silver[/COLOR]',
    'darkgray':'[COLOR darkgray]DarkGray[/COLOR]',
    'gray':'[COLOR gray]Gray[/COLOR]',
    'dimgray':'[COLOR dimgray]DimGray[/COLOR]',
    'lightslategray':'[COLOR lightslategray]LightSlateGray[/COLOR]',
    'slategray':'[COLOR slategray]SlateGray[/COLOR]',
    'darkslategray':'[COLOR darkslategray]DarkSlateGray[/COLOR]',
    'black':'[COLOR black]Black[/COLOR]'
}


coloredToLowered = {
    None:None,
    '[COLOR indianred]IndianRed[/COLOR]':'indianred',
    '[COLOR lightcoral]LightCoral[/COLOR]':'lightcoral',
    '[COLOR salmon]Salmon[/COLOR]':'salmon',
    '[COLOR darksalmon]DarkSalmon[/COLOR]':'darksalmon',
    '[COLOR lightsalmon]LightSalmon[/COLOR]':'lightsalmon',
    '[COLOR crimson]Crimson[/COLOR]':'crimson',
    '[COLOR red]Red[/COLOR]':'red',
    '[COLOR firebrick]FireBrick[/COLOR]':'firebrick',
    '[COLOR darkred]DarkRed[/COLOR]':'darkred',
    
    '[COLOR pink]Pink[/COLOR]':'pink',
    '[COLOR lightpink]LightPink[/COLOR]':'lightpink',
    '[COLOR hotpink]HotPink[/COLOR]':'hotpink',
    '[COLOR deeppink]DeepPink[/COLOR]':'deeppink',
    '[COLOR mediumvioletred]MediumVioletRed[/COLOR]':'mediumvioletred',
    '[COLOR palevioletred]PaleVioletRed[/COLOR]':'palevioletred',
    
    '[COLOR lightsalmon]LightSalmon[/COLOR]':'lightsalmon',
    '[COLOR coral]Coral[/COLOR]':'coral',
    '[COLOR tomato]Tomato[/COLOR]':'tomato',
    '[COLOR orangered]OrangeRed[/COLOR]':'orangered',
    '[COLOR darkorange]DarkOrange[/COLOR]':'darkorange',
    '[COLOR orange]Orange[/COLOR]':'orange',
    
    '[COLOR gold]Gold[/COLOR]':'gold',
    '[COLOR yellow]Yellow[/COLOR]':'yellow',
    '[COLOR lightyellow]LightYellow[/COLOR]':'lightyellow',
    '[COLOR lemonchiffon]LemonChiffon[/COLOR]':'lemonchiffon',
    '[COLOR lightgoldenrodyellow]LightGoldenrodYellow[/COLOR]':'lightgoldenrodyellow',
    '[COLOR papayawhip]PapayaWhip[/COLOR]':'papayawhip',
    '[COLOR moccasin]Moccasin[/COLOR]':'moccasin',
    '[COLOR peachpuff]PeachPuff[/COLOR]':'peachpuff',
    '[COLOR palegoldenrod]PaleGoldenrod[/COLOR]':'palegoldenrod',
    '[COLOR khaki]Khaki[/COLOR]':'khaki',
    '[COLOR darkkhaki]DarkKhaki[/COLOR]':'darkkhaki',
    
    '[COLOR lavender]Lavender[/COLOR]':'lavender',
    '[COLOR thistle]Thistle[/COLOR]':'thistle',
    '[COLOR plum]Plum[/COLOR]':'plum',
    '[COLOR violet]Violet[/COLOR]':'violet',
    '[COLOR orchid]Orchid[/COLOR]':'orchid',
    '[COLOR fuchsia]Fuchsia[/COLOR]':'fuchsia',
    '[COLOR magenta]Magenta[/COLOR]':'magenta',
    '[COLOR mediumorchid]MediumOrchid[/COLOR]':'mediumorchid',
    '[COLOR mediumpurple]MediumPurple[/COLOR]':'mediumpurple',
    '[COLOR amethyst]Amethyst[/COLOR]':'amethyst',
    '[COLOR blueviolet]BlueViolet[/COLOR]':'blueviolet',
    '[COLOR darkviolet]DarkViolet[/COLOR]':'darkviolet',
    '[COLOR darkorchid]DarkOrchid[/COLOR]':'darkorchid',
    '[COLOR darkmagenta]DarkMagenta[/COLOR]':'darkmagenta',
    '[COLOR purple]Purple[/COLOR]':'purple',
    '[COLOR indigo]Indigo[/COLOR]':'indigo',
    '[COLOR slateblue]SlateBlue[/COLOR]':'slateblue',
    '[COLOR darkslateblue]DarkSlateBlue[/COLOR]':'darkslateblue',
    '[COLOR mediumslateblue]MediumSlateBlue[/COLOR]':'mediumslateblue',
    
    '[COLOR greenyellow]GreenYellow[/COLOR]':'greenyellow',
    '[COLOR chartreuse]Chartreuse[/COLOR]':'chartreuse',
    '[COLOR lawngreen]LawnGreen[/COLOR]':'lawngreen',
    '[COLOR lime]Lime[/COLOR]':'lime',
    '[COLOR limegreen]LimeGreen[/COLOR]':'limegreen',
    '[COLOR palegreen]PaleGreen[/COLOR]':'palegreen',
    '[COLOR lightgreen]LightGreen[/COLOR]':'lightgreen',
    '[COLOR mediumspringgreen]MediumSpringGreen[/COLOR]':'mediumspringgreen',
    '[COLOR springgreen]SpringGreen[/COLOR]':'springgreen',
    '[COLOR mediumseagreen]MediumSeaGreen[/COLOR]':'mediumseagreen',
    '[COLOR seagreen]SeaGreen[/COLOR]':'seagreen',
    '[COLOR forestgreen]ForestGreen[/COLOR]':'forestgreen',
    '[COLOR green]Green[/COLOR]':'green',
    '[COLOR darkgreen]DarkGreen[/COLOR]':'darkgreen',
    '[COLOR yellowgreen]YellowGreen[/COLOR]':'yellowgreen',
    '[COLOR olivedrab]OliveDrab[/COLOR]':'olivedrab',
    '[COLOR olive]Olive[/COLOR]':'olive',
    '[COLOR darkolivegreen]DarkOliveGreen[/COLOR]':'darkolivegreen',
    '[COLOR mediumaquamarine]MediumAquamarine[/COLOR]':'mediumaquamarine',
    '[COLOR darkseagreen]DarkSeaGreen[/COLOR]':'darkseagreen',
    '[COLOR lightseagreen]LightSeaGreen[/COLOR]':'lightseagreen',
    '[COLOR darkcyan]DarkCyan[/COLOR]':'darkcyan',
    '[COLOR teal]Teal[/COLOR]':'teal',
    
    '[COLOR aqua]Aqua[/COLOR]':'aqua',
    '[COLOR cyan]Cyan[/COLOR]':'cyan',
    '[COLOR lightcyan]LightCyan[/COLOR]':'lightcyan',
    '[COLOR paleturquoise]PaleTurquoise[/COLOR]':'paleturquoise',
    '[COLOR aquamarine]Aquamarine[/COLOR]':'aquamarine',
    '[COLOR turquoise]Turquoise[/COLOR]':'turquoise',
    '[COLOR mediumturquoise]MediumTurquoise[/COLOR]':'mediumturquoise',
    '[COLOR darkturquoise]DarkTurquoise[/COLOR]':'darkturquoise',
    '[COLOR cadetblue]CadetBlue[/COLOR]':'cadetblue',
    '[COLOR steelblue]SteelBlue[/COLOR]':'steelblue',
    '[COLOR lightsteelblue]LightSteelBlue[/COLOR]':'lightsteelblue',
    '[COLOR powderblue]PowderBlue[/COLOR]':'powderblue',
    '[COLOR lightblue]LightBlue[/COLOR]':'lightblue',
    '[COLOR skyblue]SkyBlue[/COLOR]':'skyblue',
    '[COLOR lightskyblue]LightSkyBlue[/COLOR]':'lightskyblue',
    '[COLOR deepskyblue]DeepSkyBlue[/COLOR]':'deepskyblue',
    '[COLOR dodgerblue]DodgerBlue[/COLOR]':'dodgerblue',
    '[COLOR cornflowerblue]CornflowerBlue[/COLOR]':'cornflowerblue',
    '[COLOR mediumslateblue]MediumSlateBlue[/COLOR]':'mediumslateblue',
    '[COLOR royalblue]RoyalBlue[/COLOR]':'royalblue',
    '[COLOR blue]Blue[/COLOR]':'blue',
    '[COLOR mediumblue]MediumBlue[/COLOR]':'mediumblue',
    '[COLOR darkblue]DarkBlue[/COLOR]':'darkblue',
    '[COLOR navy]Navy[/COLOR]':'navy',
    '[COLOR midnightblue]MidnightBlue[/COLOR]':'midnightblue',
    
    '[COLOR cornsilk]Cornsilk[/COLOR]':'cornsilk',
    '[COLOR blanchedalmond]BlanchedAlmond[/COLOR]':'blanchedalmond',
    '[COLOR bisque]Bisque[/COLOR]':'bisque',
    '[COLOR navajowhite]NavajoWhite[/COLOR]':'navajowhite',
    '[COLOR wheat]Wheat[/COLOR]':'wheat',
    '[COLOR burlywood]BurlyWood[/COLOR]':'burlywood',
    '[COLOR tan]Tan[/COLOR]':'tan',
    '[COLOR rosybrown]RosyBrown[/COLOR]':'rosybrown',
    '[COLOR sandybrown]SandyBrown[/COLOR]':'sandybrown',
    '[COLOR goldenrod]Goldenrod[/COLOR]':'goldenrod',
    '[COLOR darkgoldenrod]DarkGoldenrod[/COLOR]':'darkgoldenrod',
    '[COLOR peru]Peru[/COLOR]':'peru',
    '[COLOR chocolate]Chocolate[/COLOR]':'chocolate',
    '[COLOR saddlebrown]SaddleBrown[/COLOR]':'saddlebrown',
    '[COLOR sienna]Sienna[/COLOR]':'sienna',
    '[COLOR brown]Brown[/COLOR]':'brown',
    '[COLOR maroon]Maroon[/COLOR]':'maroon',
    
    '[COLOR white]White[/COLOR]':'white',
    '[COLOR snow]Snow[/COLOR]':'snow',
    '[COLOR honeydew]Honeydew[/COLOR]':'honeydew',
    '[COLOR mintcream]MintCream[/COLOR]':'mintcream',
    '[COLOR azure]Azure[/COLOR]':'azure',
    '[COLOR aliceblue]AliceBlue[/COLOR]':'aliceblue',
    '[COLOR ghostwhite]GhostWhite[/COLOR]':'ghostwhite',
    '[COLOR whitesmoke]WhiteSmoke[/COLOR]':'whitesmoke',
    '[COLOR seashell]Seashell[/COLOR]':'seashell',
    '[COLOR beige]Beige[/COLOR]':'beige',
    '[COLOR oldlace]OldLace[/COLOR]':'oldlace',
    '[COLOR floralwhite]FloralWhite[/COLOR]':'floralwhite',
    '[COLOR ivory]Ivory[/COLOR]':'ivory',
    '[COLOR antiquewhite]AntiqueWhite[/COLOR]':'antiquewhite',
    '[COLOR linen]Linen[/COLOR]':'linen',
    '[COLOR lavenderblush]LavenderBlush[/COLOR]':'lavenderblush',
    '[COLOR mistyrose]MistyRose[/COLOR]':'mistyrose',
    
    '[COLOR gainsboro]Gainsboro[/COLOR]':'gainsboro',
    '[COLOR lightgrey]LightGrey[/COLOR]':'lightgrey',
    '[COLOR silver]Silver[/COLOR]':'silver',
    '[COLOR darkgray]DarkGray[/COLOR]':'darkgray',
    '[COLOR gray]Gray[/COLOR]':'gray',
    '[COLOR dimgray]DimGray[/COLOR]':'dimgray',
    '[COLOR lightslategray]LightSlateGray[/COLOR]':'lightslategray',
    '[COLOR slategray]SlateGray[/COLOR]':'slategray',
    '[COLOR darkslategray]DarkSlateGray[/COLOR]':'darkslategray',
    '[COLOR black]Black[/COLOR]':'black'
}